language: scala
scala:
- 2.11.8
jdk:
- oraclejdk8
env:
  secure: "hZpbFzSnEnsTRTVHUA+zRqJypT/Cp4AQRfNRzyoyhCOz5SF9TJRZU6JCO4kjTJ5UZ5toNpFfE6cV+1NCP5qG64Pdi7tG7RrBIM96LMt2VvwzoTjhjuFWNjGxt/TineT9yaM4kcF1YPLOcaCMCLY1WI4XllbPcEYOO2bTQXVp+/Ewf6ImPLYpA+tzhdomUT5ccjR6Ba/rM8+yGQxtgxD1Ibt8+lz5wOPxmgimIWekCdBFZtJeTCgUbrP+gcAko0YKXZ3Z7+zD0cKFGuQuOvCvNpBUa8XByosSA6CCFOUkuvxoDZN31IgCECQo07EaD2uWn+rWHy82D4IGCZ3cwLfCgdgAP/DL9UemYLcmS2Q6orLnNnI1ZHF0pxpAUjsaClOoJJjWUJYC0Na64jz8ZbjMg3hwfUZ3K9XZh0MIPIx4pBPVzTl2Tpiplg/cxjKON9MTvYxBqJm6x4GO4rnViuYSlRBXVXsl+3B6MO0B9Yq4TStq+GgMnY+7S/RFqNpKRJh4Ne/Z4Vmig8FSU+M+p9qA2L+p1puks8U0GYIrZp2bO8TvJz1X4Mof6JRvRfeqvOTsKA/2/KvSKvHmOtztCQxJ2Q/CRuYvjZQmmXLslrb7p+EmbR45JgXZiEMy7fkI3pWooIus9mkJ3OLgmAm5SWFMZxmXuabHmHrMf18FAD8Ol6g="
  secure: "aL6kk7nGws6/kRdr0KHl+2R/sIL/S+Woruk3oUDmSkjIFTNLIp2d73XiU3B8Ahz1z8KCe80GI783F6inUBuxZ9rjlU+H53vz7Fl7/LyGutdHkcKcaqYdQU03e7+aHIodDWQ1fWIH0WWRbYaySHyKgU6F/l3rEqVqFQB1m4CEdgJIKBc+kleVPC3wDKqe8ZAUsTaaZpY4DuC9xWQXnmjhxIMbPQw1habf1G/6RdMCQhj3jO04/nGYHVE9uda121f60ZMM/31o29I9gHKuFjuhxIO/x0bF06rz8nigs4dCu+Jlc2SFNEuz3XrBPhg07MrY6fdZM+7vQGxnZ2UebjOGGHofErpL8R/Xirx8suQFnnL1t8XVEpbDulFexAK+kvWnEhuCMeVCSSfHSSrIuEgaR1BaOdAyrUtenZ0rN3O3hms709hI5MjulRtqRsoCgI6kzJElVBkuZUOdWKR17gUR92mAH7EB+ZNvvoJVCcMSX8SZFh+LVgCh6wx9COamCs15GVTq5TDiGkSFOjC64P44ICadLqL5oc2PluIj7CaSQNlzt7R5yLoSL4wSUhXA1S6EqjoXaRbr4/VvS3gy9dL5lcKq2l0Ggv24gZgAwVAT0FjoAMuZRbr7M6jG7WWu2jCjBpXQPBcVc04n1I1QtVZdQ2s16U+Nnraecj2504rgzd8="
before_script:
- openssl aes-256-cbc -K $encrypted_913079356b93_key -iv $encrypted_913079356b93_iv
  -in sonatype.sbt.enc -out sonatype.sbt -d
- unset SBT_OPTS
- chmod +x ./bin/snapshot
script:
- "./bin/snapshot --all"
